name: dealsdray_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  animated_splash_screen: ^1.3.0
  animated_toggle_switch: ^0.8.3
  cupertino_icons: ^1.0.8
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.2
  http: ^1.2.2
  lottie: ^3.1.3
  shimmer: ^3.0.0
  velocity_x: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/animations/
    - lib/assets/fonts/
    - lib/assets/img/

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FFFFFF"
  #background_image: "lib/assets/img/"
  image: "lib/assets/img/dealsdray_img.png"

